<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFVu5oib\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFVu5oib/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFVu5oib.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFVu5oib\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFVu5oib\App_KernelDevDebugContainer([
    'container.build_hash' => 'FVu5oib',
    'container.build_id' => 'ad1d22f1',
    'container.build_time' => 1581521754,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFVu5oib');
